import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Check, Download, Share2, Shield } from "lucide-react";
import { toast } from "sonner";

export default function CodeDisplay({ residence, units }) {
  const [copiedId, setCopiedId] = useState(null);

  const copyToClipboard = (text, id) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    toast.success("Code copied to clipboard");
    setTimeout(() => setCopiedId(null), 2000);
  };

  const copyAllCodes = () => {
    let text = `${residence.building_name} - Access Codes\n\n`;
    text += `Building Security Code: ${residence.security_code}\n\n`;
    text += `Unit Codes:\n`;
    units.forEach((u) => {
      text += `Unit ${u.unit_label} - ${u.unit_code}\n`;
    });
    navigator.clipboard.writeText(text);
    toast.success("All codes copied to clipboard");
  };

  const downloadCodes = () => {
    let text = `${residence.building_name} - Access Codes\n`;
    text += `${"=".repeat(40)}\n\n`;
    text += `Building Security Code: ${residence.security_code}\n\n`;
    text += `Unit Codes:\n`;
    text += `${"-".repeat(30)}\n`;
    units.forEach((u) => {
      text += `Unit ${u.unit_label}: ${u.unit_code}\n`;
    });
    text += `\n${"-".repeat(30)}\n`;
    text += `Total codes: ${units.length} student + 1 security\n`;
    text += `Generated by ResLiving\n`;

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${residence.building_name.replace(/\s+/g, "_")}_codes.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareCodes = async () => {
    let text = `${residence.building_name} - Access Codes\n\n`;
    text += `Security Code: ${residence.security_code}\n\n`;
    units.forEach((u) => {
      text += `Unit ${u.unit_label}: ${u.unit_code}\n`;
    });

    if (navigator.share) {
      await navigator.share({ title: `${residence.building_name} Codes`, text });
    } else {
      copyAllCodes();
    }
  };

  if (!residence || !units) return null;

  return (
    <div className="space-y-4">
      {/* Security Code */}
      <div className="p-5 rounded-2xl border-2 border-primary/20 bg-primary/[0.02]">
        <div className="flex items-center gap-2 mb-3">
          <Shield className="w-4 h-4 text-primary" />
          <span className="text-sm font-semibold text-foreground">Building Security Code</span>
        </div>
        <div className="flex items-center justify-between">
          <code className="text-2xl font-mono font-bold text-primary tracking-widest">
            {residence.security_code}
          </code>
          <Button
            variant="outline"
            size="sm"
            onClick={() => copyToClipboard(residence.security_code, "security")}
          >
            {copiedId === "security" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
          </Button>
        </div>
      </div>

      {/* Actions */}
      <div className="flex gap-2">
        <Button variant="outline" size="sm" onClick={copyAllCodes} className="flex-1">
          <Copy className="w-3.5 h-3.5 mr-2" />
          Copy All
        </Button>
        <Button variant="outline" size="sm" onClick={downloadCodes} className="flex-1">
          <Download className="w-3.5 h-3.5 mr-2" />
          Download
        </Button>
        <Button variant="outline" size="sm" onClick={shareCodes} className="flex-1">
          <Share2 className="w-3.5 h-3.5 mr-2" />
          Share
        </Button>
      </div>

      {/* Unit Codes */}
      <div className="p-5 rounded-2xl border border-border bg-card">
        <h3 className="text-sm font-semibold text-foreground mb-4">Unit Codes ({units.length})</h3>
        <div className="space-y-2 max-h-96 overflow-y-auto pr-2">
          {units.map((unit) => (
            <div
              key={unit.id}
              className="flex items-center justify-between py-2.5 px-3 rounded-lg hover:bg-muted/50 transition-colors group"
            >
              <div className="flex items-center gap-3">
                <span className="text-xs font-medium text-muted-foreground w-16">Unit {unit.unit_label}</span>
                <code className="text-sm font-mono font-semibold text-foreground tracking-wider">
                  {unit.unit_code}
                </code>
              </div>
              <Button
                variant="ghost"
                size="sm"
                className="opacity-0 group-hover:opacity-100 transition-opacity h-7 w-7 p-0"
                onClick={() => copyToClipboard(unit.unit_code, unit.id)}
              >
                {copiedId === unit.id ? <Check className="w-3 h-3 text-green-600" /> : <Copy className="w-3 h-3" />}
              </Button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}